### ISSUE TITLE
Delist Repomaker from Flathub

### ISSUE THREAD

**Issue by AltNico** [flathub/org.fdroid.Repomaker#6]
Dear Flathub maintainers (@barthalion, @bilelmoussaoui, etc.),

I hereby ask you to delist Repomaker from Flathub.org.

During the last year, we at F-Droid weren't able to maintain Repomaker due to the lack of volunteers. I'm embarrassed to see that we might be one of the last projects on Repomaker still using highly outdated runtimes (#4) and extensions (#5). Under the hood, it looks even worse. Please see [fdroid/repomaker#233](https://gitlab.com/fdroid/repomaker/-/issues/233) for a full descriptions with links on how much Repomaker is stuck inside a dependency hell. Especially the issue's description and [my last post from today](https://gitlab.com/fdroid/repomaker/-/issues/233#note_359103921) should be of most interest for you.

As this repository is merely a mirror of [our upstream Flatpak repo](https://gitlab.com/fdroid/fdroid-repomaker-flatpak), feel free to archive or delete this project here at GitHub.

Thank you for your time,

Nico

**Comment by barthalion** [comment]
Hi @Altnico, sorry to hear about issues with Repomaker. It will be automatically delisted after adding `eol` message as described at https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life

Please poke me if it fails to build for some reason, I'll handle it manually then.

**Comment by AltNico** [comment]
Thanks for your response, @barthalion, and thanks a lot for that link to the wiki. I totally forgot that there was a wiki hidden in the flathub project.

Sadly, by simply putting an _flathub.json_ the build failed because the manifest no longer works. I've tried [a lot of different things](https://github.com/flathub/org.fdroid.Repomaker/commits/master), but I just can't get it working.

Would you mind to handle it manually? Thanks a lot!

**Comment by barthalion** [comment]
Done, should be visible after a new build of different app is pushed to repos. Thanks!
