### ISSUE TITLE
make available on other arches besides x86_64

### ISSUE THREAD

**Issue by eighthave** [flathub/org.fdroid.Repomaker#8]
* searching https://flathub.org for "repomaker" finds it
* https://flathub.org/apps/details/org.fdroid.Repomaker
* but `flatpak install flathub org.fdroid.Repomaker` fails

```console
$ cat /etc/issue
Raspbian GNU/Linux 10 \n \l

$ sudo apt install flatpak
$ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
$ sudo reboot
...
$ flatpak install flathub org.fdroid.Repomaker
Looking for matches…
error: Nothing matches org.fdroid.Repomaker in remote flathub
$ 
```

@cpba any ideas?

**Comment by cpba** [comment]
It fails because you're trying to install on arm, but the flathub.json
included with our manifest blacklists arm and only builds for amd64.

Keep in mind that only removing that check isn't enough, some of our python
dependencies are installed using amd64 specific wheels and will need to be
fixed before this starts building on arm.

**Comment by eighthave** [comment]
duh of course, sorry.  I would love to make it available on arm and aarch64.

**Comment by eighthave** [comment]
I looked through it some more. This should be easy enough to do on any arch where OpenJDK is available, now that all the dependencies are Python.  I'm guessing that `none-any.whl` in the file name means it works on any arch.  Looks like only two wheels are set to use the x86_64 binaries:
* kiwisolver-1.2.0-cp38-cp38-manylinux1_x86_64.whl
* matplotlib-3.3.2-cp38-cp38-manylinux1_x86_64.whl

Then there are tarballs, which I'm guessing are source tarballs.

**Comment by eighthave** [comment]
Does this mean that GNOME is not available on arm?

```console
pi@raspbian $ flatpak-builder builddir --install-deps-from=flathub --user --install --force-clean --ccache org.fdroid.Repomaker.json
Dependency Sdk: org.gnome.Sdk 3.38
Looking for matches…
error: Nothing matches org.gnome.Sdk in remote flathub
Error installing deps: running `flatpak --user install flathub -y org.gnome.Sdk/arm/3.38`: Child process exited with code 1
```

**Comment by cpba** [comment]
> I looked through it some more. This should be easy enough to do on any arch where OpenJDK is available, now that all the dependencies are Python. I'm guessing that none-any.whl in the file name means it works on any arch. Looks like only two wheels are set to use the x86_64 binaries:

It's a bit puzzling for me that this is the case, those dependencies are automatically generated and the script was made to avoid this kind of situation. Looking at kiwisolver I'm seeing all the wheels are platform specific and that no 32bit arm wheels are provided at all, might this be what's tripping up the script?

It'd be easy enough to fix this manually, but it would make maintaining the manifest more cumbersome in the future.

> Does this mean that GNOME is not available on arm?

edit: 3.38 is not available but 3.36 shows up on flathub, I don't have the necessary hardware to test whether it actually works. If it does it'd be an easy enough downgrade for the time being.

**Comment by Erick555** [comment]
gnome runtime version 3.38 is available only for `x86_64` and `aarch64`. Native 32bit arches aren't supported anymore.

**Comment by eighthave** [comment]
How can I get more info on the arch stuff in Flatpak, like the arches available for a given package?  I've looked for docs and arch listing but haven't found anything.  I'm trying to support Raspbian which is 32-bit.

**Comment by cpba** [comment]
There's no documentation per se, but you can see what's available from the command line.

For example, this would show you all flathub packages with arm support:

    flatpak remote-ls flathub --arch=arm

Keep in mind that `org.gnome.Platform.Compat.arm` is an extension rather than an actual runtime, this is what confused me earlier.

**Comment by eighthave** [comment]
What is `org.gnome.Platform.Compat.arm` ?  It doesn't come up in my searches.

I'm running a build using `org.gnome.Sdk` 3.36 and it seems to be working on ARM.  Is there a way to set the version of dependencies per-arch?  It would probably also be fine to use 3.36 for all arches.

**Comment by eighthave** [comment]
Also, I looked around for how to patch a build.  I want to remove one line from _androguard_'s _setup.py_ to remove the _matplotlib_ dependency, since Repomaker does not use that part of _androguard_ at all, and those are the only arch-specific Wheel packages.

**Comment by Erick555** [comment]
3.36 have arm support but it may be eol within couple of months.

**Comment by cpba** [comment]
> What is org.gnome.Platform.Compat.arm ? It doesn't come up in my searches.

It's an extension meant for offering 32bit support on 64bit systems.

> I'm running a build using org.gnome.Sdk 3.36 and it seems to be working on ARM. Is there a way to set the version of dependencies per-arch?

`flatpak-builder` looks for properties like `arch`, `only-arches` and `skip-arches` in the manifest to do this kind of thing. However, I have only ever used this with modules and build options, I don't know if it'd also work for the runtime.

> Also, I looked around for how to patch a build. I want to remove one line from androguard's setup.py to remove the matplotlib dependency, since Repomaker does not use that part of androguard at all, and those are the only arch-specific Wheel packages.

There's a number of ways to do this, the easiest and most common is to define a `patch` source in the module, `flatpak-builder` will automatically apply the patch.

However, given that you're using the `simple` buildsystem already and you only want to delete a single line, you might want to do so by including a `sed` one-liner in the `build-commands` instead.

**Comment by eighthave** [comment]
I made a fake, placeholder version of the _matplotlib_.  Another possible approach would be to manually unpack the _androguard_ tarball, then remove _matplotlib_ from _setup.py_, then run `pip3 install -e unpacked-androguard`. The fake _matplotlib_ works on GitLab CI at least: 
https://gitlab.com/fdroid/fdroid-repomaker-flatpak/-/pipelines/217065910

Hopefully it'll work on the flathub builders too.

**Comment by eighthave** [comment]
Oh well, that failed: https://flathub.org/builds/#/builders/6/builds/2034 I'm open to suggestions

**Comment by cpba** [comment]
@eighthave If all you need is to skip installing matplotlib you could try a disgusting hack like this:

https://gitlab.com/fdroid/fdroid-repomaker-flatpak/-/merge_requests/37

But are you sure this is a good idea?

**Comment by eighthave** [comment]
I ran into other issues trying to skip _matplotlib_, so now I'm trying to build it from source.  Now its failing since it needs to find _freetype_. Any tips?

**Comment by cpba** [comment]
Every runtime has `libfreetype`, most apps need it.

Could it be asking for the [python module](https://pypi.org/project/freetype-py/) instead?

**Comment by eighthave** [comment]
Looks like it is not finding the built-in one:

> error: Failed to download FreeType. Please download one of ['https://downloads.sourceforge.net/project/freetype/freetype2/2.6.1/freetype-2.6.1.tar.gz', 'https://download.savannah.gnu.org/releases/freetype/freetype-2.6.1.tar.gz'] and extract it into build/freetype-2.6.1 at the top-level of the source repository.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rk6byfct/matplotlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rk6byfct/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-f33bjvcq/install-record.txt --single-version-externally-managed --prefix /app --compile Check the logs for full command output.

**Comment by eighthave** [comment]
https://github.com/flathub/de.rwth_aachen.ient.RDPlot has working _matplotlib_, thanks to #flatpak !  Testing the update now.
